# Generated by Django 5.1.3 on 2024-11-25 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='sessao',
        ),
        migrations.AddField(
            model_name='carrinho',
            name='name',
            field=models.CharField(default='test', max_length=40),
            preserve_default=False,
        ),
    ]
