# Generated by Django 5.1.3 on 2024-11-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0002_remove_carrinho_sessao_carrinho_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='name',
            field=models.CharField(default='test', max_length=40),
        ),
    ]
