# Generated by Django 5.1.3 on 2024-12-01 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('camiseta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.camiseta')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Em analise', max_length=25)),
                ('itens', models.ManyToManyField(related_name='itens', to='pedido.pedidoitem')),
            ],
        ),
    ]
